name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run:  echo ${{ secrets.DOCKERPAT }} | docker login -u bhhoang --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bhhoang/otawa:latest
    - name: Publish to Dockerhub
      run: docker push bhhoang/otawa:latest
